/** @type {import('@commitlint/types').UserConfig} */
export default {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'header-max-length': [2, 'always', 100],
    'subject-case': [2, 'never', ['upper-case', 'pascal-case']],
    'type-enum': [
      2,
      'always',
      [
        'feat',
        'fix',
        'docs',
        'style',
        'refactor',
        'perf',
        'test',
        'build',
        'ci',
        'chore',
        'revert',
        'security',
      ],
    ],
    'scope-enum': [
      1,
      'always',
      [
        'web',
        'db',
        'domain',
        'integrations',
        'ui',
        'auth',
        'kanban',
        'comm',
        'overview',
        'team',
        'settings',
        'i18n',
        'infra',
        'ci',
        'deps',
        'release',
      ],
    ],
  },
};
